%% generate_all_outputs_matlab.m
% Replication package for:
% "Private Reliability and Liability Governance in Agentic AI Platforms"
%
% This MATLAB script mirrors the executable Python reference file
% generate_all_outputs.py. It uses the same primitives and Bellman objects
% as the manuscript. The publication-ready 45-panel gallery is generated by
% Python; this MATLAB file is a transparent formula-equivalent cross-check that
% reproduces the core solver, diagnostics, policy tests, and representative panels
% in separate folders so it never overwrites manuscript figures.
%
% Core structure:
% 1. Marketplace pooling with a common auditable protocol e_M(mu).
% 2. Dynamic public Bellman value W_M(mu).
% 3. Induced type values V_H^M(mu), V_L^M(mu).
% 4. Separating-accountability incentive checks: H -> R, L -> M.
% 5. Bayesian learning, stochastic path bands, policy counterfactuals,
%    and robustness diagnostics.
%
% Recommended MATLAB: R2021b or later.

clear; close all; clc;

%% Paths
this_file = mfilename('fullpath');
[this_dir,~,~] = fileparts(this_file);
root_dir = fileparts(this_dir);
fig_dir = fullfile(root_dir,'figures_matlab');
tab_dir = fullfile(root_dir,'tables_matlab');
if ~exist(fig_dir,'dir'); mkdir(fig_dir); end
if ~exist(tab_dir,'dir'); mkdir(tab_dir); end

%% Baseline parameters
par.thetaH = 0.92;
par.thetaL = 0.62;
par.kappa = 1.35;
par.gamma = 0.82;
par.L = 0.42;
par.tau = 0.115;
par.delta = 0.92;
par.mu0 = 0.50;
par.rhoM = 0.30;
par.rhoR = 0.31;
par.a = 0.95;
par.emax = 3.20;
par.lambdaM = 0.10;
par.lambdaR = 1.00;
par.nMu = 241;
par.nE = 220;
par.maxit = 2500;
par.tol = 1e-8;

S = style_spec();

%% Dynamic solution
[muGrid,W,policy,resW] = solve_pooling_bellman(par);
[VH,resH] = induced_type_values(par.thetaH,muGrid,policy,par);
[VL,resL] = induced_type_values(par.thetaL,muGrid,policy,par);

%% Figures
fig1_timing_architecture(fig_dir,S);
fig2_learning(fig_dir,S,muGrid,policy,par);
fig3_dynamic(fig_dir,S,muGrid,W,VH,VL,policy,resW,resH,resL,par);
fig4_incentives(fig_dir,S,muGrid,VH,VL,par);
fig5_policy(fig_dir,S,par);
fig6_robustness(fig_dir,S,par);

%% Tables
write_tables(tab_dir,muGrid,W,VH,VL,policy,resW,resH,resL,par);
write_extended_validation_tables(tab_dir,muGrid,W,VH,VL,policy,par);

fprintf('MATLAB cross-check replication completed.\nFigures: %s\nTables: %s\n',fig_dir,tab_dir);

%% ------------------------------------------------------------------------
%% Local functions
%% ------------------------------------------------------------------------
function S = style_spec()
    S.blue = [49 90 166]/255;
    S.green = [42 140 106]/255;
    S.orange = [212 122 42]/255;
    S.red = [181 74 69]/255;
    S.purple = [109 83 166]/255;
    S.gray = [93 102 115]/255;
    S.dark = [32 42 53]/255;
    S.light = [238 242 247]/255;
    S.gold = [199 154 43]/255;
    S.teal = [41 127 142]/255;
    S.lw = 1.8;
end

function y = success(theta,e,par)
    y = 1 - (1-theta).*exp(-par.kappa.*e);
end

function y = dsuccess(theta,e,par)
    y = par.kappa.*(1-theta).*exp(-par.kappa.*e);
end

function y = expected_success(mu,e,par)
    y = mu.*success(par.thetaH,e,par) + (1-mu).*success(par.thetaL,e,par);
end

function y = dexp_success(mu,e,par)
    y = mu.*dsuccess(par.thetaH,e,par) + (1-mu).*dsuccess(par.thetaL,e,par);
end

function y = posterior_success(mu,e,par)
    sh = success(par.thetaH,e,par);
    sl = success(par.thetaL,e,par);
    den = mu.*sh + (1-mu).*sl;
    y = (mu.*sh)./den;
end

function y = posterior_failure(mu,e,par)
    fh = 1-success(par.thetaH,e,par);
    fl = 1-success(par.thetaL,e,par);
    den = mu.*fh + (1-mu).*fl;
    y = (mu.*fh)./den;
end

function y = pi_m_public(mu,e,par)
    q = expected_success(mu,e,par);
    demand = par.a + par.gamma.*q;
    exposure = par.lambdaM.*par.L.*(1-q);
    y = par.rhoM.*demand.^2 - par.tau.*e.^2 - exposure;
end

function y = pi_m_type(mu,theta,e,par)
    q = expected_success(mu,e,par);
    demand = par.a + par.gamma.*q;
    exposure = par.lambdaM.*par.L.*(1-success(theta,e,par));
    y = par.rhoM.*demand.^2 - par.tau.*e.^2 - exposure;
end

function y = pi_r_signal(mu_signal,theta,e,par)
    q = expected_success(mu_signal,e,par);
    demand = par.a + par.gamma.*q;
    exposure = par.lambdaR.*par.L.*(1-success(theta,e,par));
    y = par.rhoR.*demand.^2 - par.tau.*e.^2 - exposure;
end

function [eopt,popt] = static_opt(fun,par,n)
    if nargin < 3; n = 1200; end
    grid = linspace(0,par.emax,n);
    vals = fun(grid);
    [popt,idx] = max(vals);
    eopt = grid(idx);
end

function [muGrid,W,policy,resid] = solve_pooling_bellman(par)
    muGrid = linspace(0.001,0.999,par.nMu);
    eGrid = linspace(0,par.emax,par.nE);
    W = zeros(size(muGrid));
    policy = zeros(size(muGrid));
    resid = [];
    for it = 1:par.maxit
        Wnew = zeros(size(W));
        pnew = zeros(size(policy));
        for i = 1:numel(muGrid)
            mu = muGrid(i);
            ps = posterior_success(mu,eGrid,par);
            pf = posterior_failure(mu,eGrid,par);
            ps = min(max(ps,muGrid(1)),muGrid(end));
            pf = min(max(pf,muGrid(1)),muGrid(end));
            q = expected_success(mu,eGrid,par);
            cont = q.*interp1(muGrid,W,ps,'linear') + (1-q).*interp1(muGrid,W,pf,'linear');
            vals = pi_m_public(mu,eGrid,par) + par.delta.*cont;
            [Wnew(i),idx] = max(vals);
            pnew(i) = eGrid(idx);
        end
        r = max(abs(Wnew-W));
        resid = [resid; r]; %#ok<AGROW>
        W = Wnew;
        policy = pnew;
        if r < par.tol; break; end
    end
end

function [V,resid] = induced_type_values(theta,muGrid,policy,par)
    V = zeros(size(muGrid));
    resid = [];
    for it = 1:par.maxit
        Vnew = zeros(size(V));
        for i = 1:numel(muGrid)
            mu = muGrid(i);
            e = policy(i);
            ps = posterior_success(mu,e,par);
            pf = posterior_failure(mu,e,par);
            ps = min(max(ps,muGrid(1)),muGrid(end));
            pf = min(max(pf,muGrid(1)),muGrid(end));
            q = success(theta,e,par);
            cont = q.*interp1(muGrid,V,ps,'linear') + (1-q).*interp1(muGrid,V,pf,'linear');
            Vnew(i) = pi_m_type(mu,theta,e,par) + par.delta.*cont;
        end
        r = max(abs(Vnew-V));
        resid = [resid; r]; %#ok<AGROW>
        V = Vnew;
        if r < par.tol; break; end
    end
end

function v = perpetual_value(pi,par)
    v = pi./(1-par.delta);
end

function A = accountability_values(par,n)
    if nargin < 2; n = 1200; end
    [A.e_H_R,A.pi_H_R] = static_opt(@(e)pi_r_signal(1.0,par.thetaH,e,par),par,n);
    [A.e_L_R_mimic,A.pi_L_R_mimic] = static_opt(@(e)pi_r_signal(1.0,par.thetaL,e,par),par,n);
    [A.e_L_M,A.pi_L_M] = static_opt(@(e)pi_m_type(0.0,par.thetaL,e,par),par,n);
    [A.e_H_M_dev,A.pi_H_M_dev] = static_opt(@(e)pi_m_type(0.0,par.thetaH,e,par),par,n);
    A.U_H_R = perpetual_value(A.pi_H_R,par);
    A.U_L_R_mimic = perpetual_value(A.pi_L_R_mimic,par);
    A.U_L_M = perpetual_value(A.pi_L_M,par);
    A.U_H_M_dev = perpetual_value(A.pi_H_M_dev,par);
end

function M = separating_ic_margins(par)
    A = accountability_values(par);
    M = A;
    M.high_accountability_margin = A.U_H_R - A.U_H_M_dev;
    M.low_antimimic_margin = A.U_L_M - A.U_L_R_mimic;
end

function [marginH,marginL] = pooling_deviation_margins(VH,VL,par)
    A = accountability_values(par);
    marginH = VH - A.U_H_R;
    marginL = VL - A.U_L_R_mimic;
end

function c = classify_governance_static(mu,L,par)
    parx = par;
    parx.L = L;
    [~,piH] = static_opt(@(e)pi_m_type(mu,parx.thetaH,e,parx),parx,420);
    [~,piL] = static_opt(@(e)pi_m_type(mu,parx.thetaL,e,parx),parx,420);
    A = accountability_values(parx,420);
    poolH = perpetual_value(piH,parx) - A.U_H_R;
    poolL = perpetual_value(piL,parx) - A.U_L_R_mimic;
    pooling = (poolH >= 0) && (poolL >= 0);
    separating = (A.U_H_R - A.U_H_M_dev >= 0) && (A.U_L_M - A.U_L_R_mimic >= 0);
    if pooling && separating
        c = 3;
    elseif pooling
        c = 1;
    elseif separating
        c = 2;
    else
        c = 0;
    end
end

function err = martingale_error(mu,e,par)
    q = expected_success(mu,e,par);
    err = q.*posterior_success(mu,e,par) + (1-q).*posterior_failure(mu,e,par) - mu;
end

function paths = simulate_belief_paths(theta,muGrid,policy,par,reps,horizon,seed)
    rng(seed,'twister');
    paths = zeros(reps,horizon+1);
    paths(:,1) = par.mu0;
    for r = 1:reps
        mu = par.mu0;
        for t = 1:horizon
            e = interp1(muGrid,policy,mu,'linear','extrap');
            y = rand < success(theta,e,par);
            if y
                mu = posterior_success(mu,e,par);
            else
                mu = posterior_failure(mu,e,par);
            end
            mu = min(max(mu,0.001),0.999);
            paths(r,t+1) = mu;
        end
    end
end

function [egrid,comps] = marginal_decomposition(mu0,muGrid,W,par)
    egrid = linspace(0.02,par.emax,280);
    dW = gradient(W,muGrid);
    comps = zeros(numel(egrid),4);
    h = 1e-4;
    for i = 1:numel(egrid)
        e = egrid(i);
        q = expected_success(mu0,e,par);
        dq = dexp_success(mu0,e,par);
        ms = posterior_success(mu0,e,par);
        mf = posterior_failure(mu0,e,par);
        dms = (posterior_success(mu0,e+h,par)-posterior_success(mu0,e-h,par))/(2*h);
        dmf = (posterior_failure(mu0,e+h,par)-posterior_failure(mu0,e-h,par))/(2*h);
        current = (pi_m_public(mu0,e+h,par)-pi_m_public(mu0,e-h,par))/(2*h);
        successProb = par.delta*dq*(interp1(muGrid,W,ms,'linear')-interp1(muGrid,W,mf,'linear'));
        posteriorLoc = par.delta*(q*interp1(muGrid,dW,ms,'linear')*dms + (1-q)*interp1(muGrid,dW,mf,'linear')*dmf);
        comps(i,:) = [current, successProb, posteriorLoc, current+successProb+posteriorLoc];
    end
end

function muPost = audit_posterior(mu,accuracy,favorable)
    if favorable
        num = mu*accuracy;
        den = mu*accuracy + (1-mu)*(1-accuracy);
    else
        num = mu*(1-accuracy);
        den = mu*(1-accuracy) + (1-mu)*accuracy;
    end
    muPost = num/den;
end

function rows = policy_counterfactuals(par)
    configs = { ...
        'Baseline', par, par.mu0, 'Original primitives'; ...
        'Liability mandate', setfield(par,'L',1.00), par.mu0, 'Higher direct failure exposure'; ... %#ok<SFLD>
        'Certified audit', par, audit_posterior(par.mu0,0.78,true), 'Favorable public audit with 78% accuracy'; ...
        'Safe harbor', setfield(par,'lambdaR',0.72), par.mu0, 'Verified internalizers bear lower residual liability'; ... %#ok<SFLD>
        'Hybrid', setfield(setfield(par,'L',1.20),'lambdaR',0.90), audit_posterior(par.mu0,0.78,true), 'Audit plus calibrated liability' ... %#ok<SFLD>
        };
    rows = cell(size(configs,1),11);
    for i = 1:size(configs,1)
        name = configs{i,1};
        px = configs{i,2};
        mu = configs{i,3};
        note = configs{i,4};
        A = accountability_values(px);
        M = separating_ic_margins(px);
        [eM,~] = static_opt(@(e)pi_m_public(mu,e,px),px);
        succ = expected_success(mu,eM,px);
        [~,piPoolH] = static_opt(@(e)pi_m_type(mu,px.thetaH,e,px),px);
        [~,piPoolL] = static_opt(@(e)pi_m_type(mu,px.thetaL,e,px),px);
        poolH = perpetual_value(piPoolH,px) - A.U_H_R;
        poolL = perpetual_value(piPoolL,px) - A.U_L_R_mimic;
        rows(i,:) = {name, mu, px.L, px.lambdaR, eM, succ, M.high_accountability_margin, M.low_antimimic_margin, poolH, poolL, note};
    end
end


function [beliefs,outcomes,efforts] = simulate_validation_paths_full(theta,muGrid,policy,par,reps,horizon,seed)
    rng(seed + round(1000*theta),'twister');
    beliefs = zeros(reps,horizon+1);
    outcomes = zeros(reps,horizon);
    efforts = zeros(reps,horizon);
    beliefs(:,1) = par.mu0;
    for r = 1:reps
        mu = par.mu0;
        for t = 1:horizon
            e = interp1(muGrid,policy,mu,'linear','extrap');
            efforts(r,t) = e;
            y = rand < success(theta,e,par);
            outcomes(r,t) = y;
            if y
                mu = posterior_success(mu,e,par);
            else
                mu = posterior_failure(mu,e,par);
            end
            mu = min(max(mu,0.001),0.999);
            beliefs(r,t+1) = mu;
        end
    end
end

function gap = dynamic_policy_foc_gap_matlab(muGrid,W,policy,par,h)
    if nargin < 5; h = 2e-4; end
    gap = nan(size(muGrid));
    for i = 1:numel(muGrid)
        mu = muGrid(i);
        e = policy(i);
        if e <= h || e >= par.emax-h
            continue;
        end
        rhs_hi = bellman_rhs_at(mu,e+h,muGrid,W,par);
        rhs_lo = bellman_rhs_at(mu,e-h,muGrid,W,par);
        gap(i) = (rhs_hi-rhs_lo)/(2*h);
    end
end

function val = bellman_rhs_at(mu,e,muGrid,W,par)
    ps = min(max(posterior_success(mu,e,par),muGrid(1)),muGrid(end));
    pf = min(max(posterior_failure(mu,e,par),muGrid(1)),muGrid(end));
    q = expected_success(mu,e,par);
    val = pi_m_public(mu,e,par) + par.delta.*(q.*interp1(muGrid,W,ps,'linear') + (1-q).*interp1(muGrid,W,pf,'linear'));
end

function threshold = first_nonnegative_threshold(x,y)
    idx = find(y >= 0,1,'first');
    if isempty(idx); threshold = NaN; else; threshold = x(idx); end
end

function threshold = last_nonnegative_threshold(x,y)
    idx = find(y >= 0,1,'last');
    if isempty(idx); threshold = NaN; else; threshold = x(idx); end
end

function [poolH,poolL] = static_pooling_margins_at_matlab(mu,par,n)
    if nargin < 3; n = 420; end
    A = accountability_values(par,n);
    [~,piH] = static_opt(@(e)pi_m_type(mu,par.thetaH,e,par),par,n);
    [~,piL] = static_opt(@(e)pi_m_type(mu,par.thetaL,e,par),par,n);
    poolH = perpetual_value(piH,par)-A.U_H_R;
    poolL = perpetual_value(piL,par)-A.U_L_R_mimic;
end

function write_extended_validation_tables(tab_dir,muGrid,W,VH,VL,policy,par)
    %% Monte Carlo validation table, formula-equivalent to the Python reference.
    reps = 1600; horizon = 60;
    [bH,oH,eH] = simulate_validation_paths_full(par.thetaH,muGrid,policy,par,reps,horizon,145);
    [bL,oL,eL] = simulate_validation_paths_full(par.thetaL,muGrid,policy,par,reps,horizon,255);
    types = {'High type';'Low type'};
    B = {bH,bL}; O = {oH,oL}; E = {eH,eL};
    meanTerminal = zeros(2,1); p10 = zeros(2,1); p90 = zeros(2,1);
    meanFailure = zeros(2,1); meanEffort = zeros(2,1); finalFailure = zeros(2,1);
    for i = 1:2
        beliefs = B{i}; outcomes = O{i}; efforts = E{i};
        meanTerminal(i) = mean(beliefs(:,end));
        p10(i) = quantile(beliefs(:,end),0.10);
        p90(i) = quantile(beliefs(:,end),0.90);
        meanFailure(i) = mean(1-outcomes,'all');
        meanEffort(i) = mean(efforts,'all');
        finalFailure(i) = mean(1-outcomes(:,end));
    end
    Tsim = table(types,meanTerminal,p10,p90,meanFailure,meanEffort,finalFailure, ...
        'VariableNames',{'type','mean_terminal_belief','p10_terminal_belief','p90_terminal_belief','mean_visible_failure_rate','mean_protocol_effort','final_period_failure_rate'});
    writetable(Tsim,fullfile(tab_dir,'table_simulation_validation_matlab.csv'));

    %% Numerical certificates table.
    gap = dynamic_policy_foc_gap_matlab(muGrid,W,policy,par);
    egrid = linspace(0.01,par.emax,280);
    mus = [0.15 0.35 0.50 0.70 0.85];
    martGrid = zeros(numel(mus),numel(egrid));
    for i = 1:numel(mus)
        martGrid(i,:) = martingale_error(mus(i),egrid,par);
    end
    certNames = {'Maximum absolute dynamic policy FOC gap';'Maximum Bayesian martingale error on five-belief grid'};
    certVals = [max(abs(gap),[],'omitnan'); max(abs(martGrid),[],'all')];
    Tcert = table(certNames',certVals,'VariableNames',{'certificate','value'});
    writetable(Tcert,fullfile(tab_dir,'table_extended_certificates_matlab.csv'));

    %% Exact frontier thresholds, matching the manuscript's sign-test logic.
    Ls = linspace(0.05,1.40,180);
    hmargin = zeros(size(Ls)); lmargin = zeros(size(Ls));
    for i = 1:numel(Ls)
        px = par; px.L = Ls(i); M = separating_ic_margins(px);
        hmargin(i) = M.high_accountability_margin;
        lmargin(i) = M.low_antimimic_margin;
    end
    accs = linspace(0.52,0.98,150);
    poolH = zeros(size(accs)); poolL = zeros(size(accs));
    for i = 1:numel(accs)
        mu = audit_posterior(par.mu0,accs(i),true);
        [poolH(i),poolL(i)] = static_pooling_margins_at_matlab(mu,par,420);
    end
    A = linspace(0.56,0.96,48); Lgrid = linspace(0.15,1.35,48); Z = zeros(numel(Lgrid),numel(A));
    for i = 1:numel(Lgrid)
        for j = 1:numel(A)
            px = par; px.L = Lgrid(i); px.lambdaR = 0.90;
            mu = audit_posterior(px.mu0,A(j),true);
            sep = separating_ic_margins(px);
            [ph,pl] = static_pooling_margins_at_matlab(mu,px,280);
            Z(i,j) = (sep.high_accountability_margin >= 0) + (sep.low_antimimic_margin >= 0) + (ph >= 0) + (pl >= 0);
        end
    end
    frontier = {'Minimum L for nonnegative low anti-mimicry'; ...
                'Largest plotted L with nonnegative high accountability'; ...
                'Minimum audit accuracy for nonnegative pool-H margin'; ...
                'Minimum audit accuracy for nonnegative pool-L margin'; ...
                'Maximum exact feasibility-test count on hybrid grid'; ...
                'Share of hybrid grid satisfying all four exact tests'};
    thresholds = [first_nonnegative_threshold(Ls,lmargin); ...
                  last_nonnegative_threshold(Ls,hmargin); ...
                  first_nonnegative_threshold(accs,poolH); ...
                  first_nonnegative_threshold(accs,poolL); ...
                  max(Z,[],'all'); ...
                  mean(Z >= 4,'all')];
    criterion = {'Delta_L^anti >= 0';'Delta_H^acct >= 0';'Phi_H^M >= 0';'Phi_L^M >= 0';'0 <= exact test count <= 4';'exact test count = 4'};
    interpretation = {'liability threshold that deters low-type mimicry'; ...
                      'upper plotted liability exposure that preserves high-type participation'; ...
                      'audit threshold that restores high-type pooling support'; ...
                      'audit threshold that restores low-type pooling support'; ...
                      'diagnostic count, not a welfare index'; ...
                      'design-space share with simultaneous sign-test support'};
    Tfront = table(frontier,thresholds,criterion',interpretation, ...
        'VariableNames',{'frontier','threshold_value','criterion','interpretation'});
    writetable(Tfront,fullfile(tab_dir,'table_frontier_thresholds_matlab.csv'));
end

function save_panel(fig_dir,name)
    exportgraphics(gcf,fullfile(fig_dir,[name '.pdf']),'ContentType','vector');
    exportgraphics(gcf,fullfile(fig_dir,[name '.png']),'Resolution',320);
    close(gcf);
end

function configure_axes(xlab,ylab)
    grid on; box off;
    set(gca,'GridAlpha',0.18,'LineWidth',0.7);
    if ~isempty(xlab); xlabel(xlab); end
    if ~isempty(ylab); ylabel(ylab); end
end

function fig1_timing_architecture(fig_dir,S)
    figure('Color','w','Position',[100 100 1200 650]);
    axis([0 12 0 7.3]); axis off; hold on;
    text(6.0,7.02,'Agentic AI liability governance: public regime, hidden type, dynamic learning','HorizontalAlignment','center','FontSize',14,'FontWeight','bold','Color',S.dark);
    draw_box([0.35 5.55 1.8 0.84],'Private type \theta \in {H,L}',S.blue,'w');
    draw_box([2.55 5.55 2.1 0.84],'Observed regime g \in {M,R}',S.orange,'w');
    draw_box([5.10 5.55 2.35 0.84],'Public posterior \hat{\mu}_g',S.purple,'w');
    draw_box([7.95 5.55 2.25 0.84],'Safeguard effort e_g',S.green,'w');
    draw_box([10.55 5.55 1.1 0.84],'Outcome y',S.gray,'w');
    draw_arrow([2.15 5.97],[2.55 5.97]); draw_arrow([4.65 5.97],[5.10 5.97]); draw_arrow([7.45 5.97],[7.95 5.97]); draw_arrow([10.20 5.97],[10.55 5.97]);
    draw_box([0.55 3.95 2.85 0.88],'Marketplace pooling path: common auditable protocol e_M(\mu)',S.blue,'w');
    draw_box([4.05 3.95 3.15 0.88],'Separating accountability path: H \rightarrow R, L \rightarrow M',S.red,'w');
    draw_box([8.00 3.95 3.35 0.88],'Low-type mimicry test U_L^M(0) \geq U_L^R(1)',S.gold,S.dark);
    draw_arrow([2.15 5.55],[1.95 4.83]); draw_arrow([6.20 5.55],[5.72 4.83]); draw_arrow([9.10 5.55],[9.70 4.83]);
    draw_box([0.80 2.18 2.75 0.86],'Visible outcomes update \mu^S and \mu^F',S.teal,'w');
    draw_box([4.25 2.18 2.55 0.86],'Bellman continuation value W_M(\mu)',S.purple,'w');
    draw_box([7.50 2.18 3.10 0.86],'IC margins classify governance',S.green,'w');
    draw_arrow([3.55 2.61],[4.25 2.61]); draw_arrow([6.80 2.61],[7.50 2.61]);
    text(6.95,0.56,'Operational interpretation: liability, audits, and protocol design jointly determine incentives, inference, and welfare.','HorizontalAlignment','center','FontSize',9,'Color',S.gray);
    save_panel(fig_dir,'fig1_timing_architecture');
end

function draw_box(pos,txt,fc,tc)
    rectangle('Position',pos,'Curvature',0.08,'FaceColor',fc,'EdgeColor',fc*0.85,'LineWidth',1.1);
    text(pos(1)+pos(3)/2,pos(2)+pos(4)/2,txt,'HorizontalAlignment','center','VerticalAlignment','middle','FontSize',9,'Color',tc);
end

function draw_arrow(p1,p2)
    annotation('arrow',[p1(1)/12 p2(1)/12],[p1(2)/7.3 p2(2)/7.3],'LineWidth',1.0,'Color',[0.35 0.39 0.45]);
end

function fig2_learning(fig_dir,S,muGrid,policy,par)
    mu = linspace(0.02,0.98,300); eLevels = [0.20 0.95 1.70];
    figure('Color','w','Position',[100 100 560 420]); hold on;
    for e = eLevels; plot(mu,posterior_success(mu,e,par),'LineWidth',S.lw); end
    plot(mu,mu,'k--','LineWidth',1.0); title('(a) Posterior after a success'); configure_axes('prior belief \mu','posterior \mu^S'); legend('e=0.20','e=0.95','e=1.70','45-degree','Location','northwest'); save_panel(fig_dir,'fig2a_success_posterior');
    figure('Color','w','Position',[100 100 560 420]); hold on;
    for e = eLevels; plot(mu,posterior_failure(mu,e,par),'LineWidth',S.lw); end
    plot(mu,mu,'k--','LineWidth',1.0); title('(b) Posterior after a failure'); configure_axes('prior belief \mu','posterior \mu^F'); legend('e=0.20','e=0.95','e=1.70','45-degree','Location','northwest'); save_panel(fig_dir,'fig2b_failure_posterior');
    egrid = linspace(0.01,par.emax,280); spread = posterior_success(par.mu0,egrid,par)-posterior_failure(par.mu0,egrid,par);
    sh = success(par.thetaH,egrid,par); sl = success(par.thetaL,egrid,par); kl = sh.*log(sh./sl)+(1-sh).*log((1-sh)./(1-sl));
    figure('Color','w','Position',[100 100 560 420]); yyaxis left; plot(egrid,spread,'Color',S.purple,'LineWidth',S.lw); ylabel('\mu^S-\mu^F'); yyaxis right; plot(egrid,kl,'--','Color',S.red,'LineWidth',S.lw); ylabel('D_{KL}(H||L)'); title('(c) Reliability and diagnosticity diverge'); xlabel('effort e'); grid on; save_panel(fig_dir,'fig2c_diagnosticity');
    pathsH = simulate_belief_paths(par.thetaH,muGrid,policy,par,700,40,20260519); pathsL = simulate_belief_paths(par.thetaL,muGrid,policy,par,700,40,20260525); x = 0:40;
    figure('Color','w','Position',[100 100 600 420]); hold on;
    qH10 = quantile(pathsH,0.10,1); qH90 = quantile(pathsH,0.90,1); mH = mean(pathsH,1);
    qL10 = quantile(pathsL,0.10,1); qL90 = quantile(pathsL,0.90,1); mL = mean(pathsL,1);
    fill([x fliplr(x)],[qH10 fliplr(qH90)],S.green,'FaceAlpha',0.16,'EdgeColor','none');
    fill([x fliplr(x)],[qL10 fliplr(qL90)],S.orange,'FaceAlpha',0.16,'EdgeColor','none');
    plot(x,mH,'Color',S.green,'LineWidth',S.lw); plot(x,mL,'Color',S.orange,'LineWidth',S.lw); yline(par.mu0,'k--'); ylim([0 1]); title('(d) Simulated learning paths with 80% bands'); configure_axes('period','belief \mu_t'); legend('H 80% band','L 80% band','true H mean','true L mean','Location','best'); save_panel(fig_dir,'fig2d_learning_paths');
end

function fig3_dynamic(fig_dir,S,muGrid,W,VH,VL,policy,resW,resH,resL,par)
    figure('Color','w','Position',[100 100 580 420]); hold on;
    plot(muGrid,W,'Color',S.blue,'LineWidth',S.lw); plot(muGrid,VH,'Color',S.green,'LineWidth',S.lw); plot(muGrid,VL,'Color',S.orange,'LineWidth',S.lw); title('(a) Public and induced type values'); configure_axes('belief \mu','discounted value'); legend('W_M','V_H^M','V_L^M','Location','best'); save_panel(fig_dir,'fig3a_values');
    figure('Color','w','Position',[100 100 580 420]); plot(muGrid,policy,'Color',S.blue,'LineWidth',S.lw); xline(par.mu0,'k--'); title('(b) Common marketplace protocol'); configure_axes('belief \mu','e_M^*(\mu)'); save_panel(fig_dir,'fig3b_policy');
    figure('Color','w','Position',[100 100 580 420]); hold on; semilogy(resW,'Color',S.blue,'LineWidth',S.lw); semilogy(resH,'Color',S.green,'LineWidth',S.lw); semilogy(resL,'Color',S.orange,'LineWidth',S.lw); title('(c) Fixed-point residuals'); configure_axes('iteration','sup-norm residual'); legend('W_M','V_H^M','V_L^M','Location','best'); save_panel(fig_dir,'fig3c_residuals');
    [egrid,comps] = marginal_decomposition(par.mu0,muGrid,W,par);
    figure('Color','w','Position',[100 100 620 420]); hold on;
    plot(egrid,comps(:,1),'Color',S.blue,'LineWidth',S.lw); plot(egrid,comps(:,2),'Color',S.green,'LineWidth',S.lw); plot(egrid,comps(:,3),'Color',S.red,'LineWidth',S.lw); plot(egrid,comps(:,4),'Color',S.dark,'LineWidth',2.2); yline(0,'k-'); title('(d) Marginal-value decomposition at \mu_0'); configure_axes('effort e','marginal value'); legend('current payoff','success-probability','posterior-location','total','Location','best'); save_panel(fig_dir,'fig3d_marginal_decomposition');
end

function fig4_incentives(fig_dir,S,muGrid,VH,VL,par)
    Ls = linspace(0.05,1.10,180); highSep = zeros(size(Ls)); lowAnti = zeros(size(Ls));
    for i = 1:numel(Ls)
        px = par; px.L = Ls(i); M = separating_ic_margins(px);
        highSep(i) = M.high_accountability_margin; lowAnti(i) = M.low_antimimic_margin;
    end
    figure('Color','w','Position',[100 100 580 420]); plot(Ls,highSep,'Color',S.green,'LineWidth',S.lw); yline(0,'k-'); xline(par.L,'k--'); title('(a) High-type accountability IC'); configure_axes('failure exposure L','U_H^R(1)-U_H^M(0)'); save_panel(fig_dir,'fig4a_high_accountability');
    figure('Color','w','Position',[100 100 580 420]); plot(Ls,lowAnti,'Color',S.orange,'LineWidth',S.lw); yline(0,'k-'); xline(par.L,'k--'); title('(b) Low-type anti-mimicry IC'); configure_axes('failure exposure L','U_L^M(0)-U_L^R(1)'); save_panel(fig_dir,'fig4b_low_antimimic');
    [poolH,poolL] = pooling_deviation_margins(VH,VL,par);
    figure('Color','w','Position',[100 100 600 420]); hold on; plot(muGrid,poolH,'Color',S.green,'LineWidth',S.lw); plot(muGrid,poolL,'Color',S.orange,'LineWidth',S.lw); yline(0,'k-'); xline(par.mu0,'k--'); title('(c) Dynamic marketplace-pooling stability'); configure_axes('belief \mu','pooling deviation margin'); legend('H no-R-deviation','L no-R-deviation','Location','best'); save_panel(fig_dir,'fig4c_pooling_margins');
    muMap = linspace(0.05,0.95,36); LMap = linspace(0.05,1.10,36); Z = zeros(numel(LMap),numel(muMap));
    for i = 1:numel(LMap); for j = 1:numel(muMap); Z(i,j) = classify_governance_static(muMap(j),LMap(i),par); end; end
    figure('Color','w','Position',[100 100 620 440]); imagesc(muMap,LMap,Z); set(gca,'YDir','normal'); hold on; plot(par.mu0,par.L,'kx','MarkerSize',8,'LineWidth',1.5); colorbar('Ticks',[0 1 2 3],'TickLabels',{'conflict','pooling','separating','both'}); title('(d) Local governance classification'); configure_axes('prior belief \mu','failure exposure L'); save_panel(fig_dir,'fig4d_governance_map');
end

function fig5_policy(fig_dir,S,par)
    rows = policy_counterfactuals(par);
    labels = rows(:,1); high = cell2mat(rows(:,7)); low = cell2mat(rows(:,8)); succ = cell2mat(rows(:,6)); poolH = cell2mat(rows(:,9)); x = 1:numel(labels);
    figure('Color','w','Position',[100 100 660 440]); hold on; bar(x-0.18,high,0.36,'FaceColor',S.green); bar(x+0.18,low,0.36,'FaceColor',S.orange); yline(0,'k-'); set(gca,'XTick',x,'XTickLabel',labels,'XTickLabelRotation',22); title('(a) Policy effects on separating IC margins'); configure_axes('','IC margin'); legend('H accountability','L anti-mimicry','Location','best'); save_panel(fig_dir,'fig5a_policy_ic');
    figure('Color','w','Position',[100 100 660 440]); yyaxis left; bar(x-0.18,succ,0.36,'FaceColor',S.blue); ylim([0.75 1.00]); ylabel('expected success'); yyaxis right; plot(x+0.18,poolH,'-o','Color',S.red,'LineWidth',S.lw,'MarkerFaceColor',S.red); ylabel('pool H deviation margin'); set(gca,'XTick',x,'XTickLabel',labels,'XTickLabelRotation',22); title('(b) Success probability and pooling pressure'); grid on; save_panel(fig_dir,'fig5b_policy_success_pooling');
    acc = linspace(0.51,0.95,120); post = zeros(size(acc)); succAudit = zeros(size(acc));
    for i = 1:numel(acc)
        post(i) = audit_posterior(par.mu0,acc(i),true); [e,~] = static_opt(@(ee)pi_m_public(post(i),ee,par),par); succAudit(i) = expected_success(post(i),e,par);
    end
    figure('Color','w','Position',[100 100 620 430]); yyaxis left; plot(acc,post,'Color',S.purple,'LineWidth',S.lw); ylabel('posterior after favorable audit'); yyaxis right; plot(acc,succAudit,'--','Color',S.green,'LineWidth',S.lw); ylabel('expected success'); title('(c) Audit precision moves beliefs and operating success'); xlabel('audit accuracy'); grid on; save_panel(fig_dir,'fig5c_audit_precision');
end

function fig6_robustness(fig_dir,S,par)
    base = separating_ic_margins(par); baseMetric = base.low_antimimic_margin;
    specs = { ...
        '$\theta_H$','thetaH',max(0.76,par.thetaH-0.06),min(0.98,par.thetaH+0.04); ...
        '$\theta_L$','thetaL',max(0.35,par.thetaL-0.12),min(0.85,par.thetaL+0.12); ...
        '$\gamma$','gamma',par.gamma*0.75,par.gamma*1.25; ...
        '$L$','L',par.L*0.60,par.L*1.60; ...
        '$\kappa$','kappa',par.kappa*0.70,par.kappa*1.30; ...
        '$\lambda_R$','lambdaR',0.68,1.20};
    rows = cell(size(specs,1),6);
    for i = 1:size(specs,1)
        pxL = par; pxH = par; pxL.(specs{i,2}) = specs{i,3}; pxH.(specs{i,2}) = specs{i,4};
        mL = separating_ic_margins(pxL); mH = separating_ic_margins(pxH); rg = abs(mH.low_antimimic_margin-mL.low_antimimic_margin);
        rows(i,:) = {specs{i,1},specs{i,3},specs{i,4},mL.low_antimimic_margin,mH.low_antimimic_margin,rg};
    end
    ranges = cell2mat(rows(:,6)); [~,idx] = sort(ranges,'descend'); rows = rows(idx,:);
    figure('Color','w','Position',[100 100 640 470]); hold on;
    for i = 1:size(rows,1)
        lo = min(rows{i,4},rows{i,5}); hi = max(rows{i,4},rows{i,5}); plot([lo hi],[i i],'LineWidth',6,'Color',S.blue); plot([lo hi],[i i],'k.','MarkerSize',16);
    end
    xline(baseMetric,'--','Color',S.red,'LineWidth',1.2); xline(0,'k-'); set(gca,'YTick',1:size(rows,1),'YTickLabel',rows(:,1)); title('(a) Tornado sensitivity of the anti-mimicry margin'); configure_axes('low-type anti-mimicry margin',''); save_panel(fig_dir,'fig6a_tornado');
    figure('Color','w','Position',[100 100 640 440]); hold on;
    grids = {linspace(max(0.35,par.thetaL-0.16),min(0.88,par.thetaL+0.16),120),'thetaL',S.orange,'\theta_L'; linspace(0.10,0.90,120),'L',S.blue,'L'; linspace(0.55,1.30,120),'lambdaR',S.green,'\lambda_R'};
    for k = 1:size(grids,1)
        g = grids{k,1}; attr = grids{k,2}; vals = zeros(size(g));
        for i = 1:numel(g); px = par; px.(attr) = g(i); M = separating_ic_margins(px); vals(i) = M.low_antimimic_margin; end
        denom = par.(attr); x = (g-denom)./denom; plot(x,vals,'Color',grids{k,3},'LineWidth',S.lw,'DisplayName',grids{k,4});
    end
    yline(0,'k-'); xline(0,'k--'); title('(b) Local nonlinear response around the baseline'); configure_axes('relative parameter change','low-type anti-mimicry margin'); legend('Location','best'); save_panel(fig_dir,'fig6b_response_curves');
end

function write_tables(tab_dir,muGrid,W,VH,VL,policy,resW,resH,resL,par)
    Tbase = table({'theta_H';'theta_L';'kappa';'gamma';'L';'lambda_M';'lambda_R';'tau';'delta';'mu_0'}, ...
        [par.thetaH;par.thetaL;par.kappa;par.gamma;par.L;par.lambdaM;par.lambdaR;par.tau;par.delta;par.mu0], ...
        {'High-reliability type';'Low-reliability type';'Effort-to-reliability curvature';'Demand sensitivity to expected success';'Failure exposure scale';'Marketplace liability share';'Internalized liability share';'Convex safeguard cost';'Discount factor';'Initial public belief'}, ...
        'VariableNames',{'primitive','value','role'});
    writetable(Tbase,fullfile(tab_dir,'table_baseline_parameters_matlab.csv'));
    [eM,~] = static_opt(@(e)pi_m_public(par.mu0,e,par),par); [eHR,~] = static_opt(@(e)pi_r_signal(1.0,par.thetaH,e,par),par); [eLR,~] = static_opt(@(e)pi_r_signal(1.0,par.thetaL,e,par),par);
    M = separating_ic_margins(par); [poolH,poolL] = pooling_deviation_margins(VH,VL,par); [~,idx] = min(abs(muGrid-par.mu0));
    maxMart = max(abs(martingale_error(par.mu0,linspace(0.01,par.emax,500),par)));
    diagNames = {'Public Bellman final residual';'High-type induced-value final residual';'Low-type induced-value final residual';'Maximum Bayes martingale error';'Static marketplace optimal effort at mu0';'Static high-type R optimal effort';'Static low-type R mimic effort';'High accountability margin';'Low anti-mimicry margin';'Dynamic pooling H deviation margin at mu0';'Dynamic pooling L deviation margin at mu0';'Public value W_M at mu0'};
    diagVals = [resW(end);resH(end);resL(end);maxMart;eM;eHR;eLR;M.high_accountability_margin;M.low_antimimic_margin;poolH(idx);poolL(idx);interp1(muGrid,W,par.mu0,'linear')];
    Tdiag = table(diagNames',diagVals,'VariableNames',{'diagnostic','value'}); writetable(Tdiag,fullfile(tab_dir,'table_numerical_diagnostics_matlab.csv'));
    rows = policy_counterfactuals(par);
    Tpol = cell2table(rows,'VariableNames',{'scenario','mu_conditioned','L','lambdaR','eM_static','market_success','high_sep_margin','low_antimimic_margin','pool_high_margin','pool_low_margin','note'});
    writetable(Tpol,fullfile(tab_dir,'table_policy_counterfactuals_matlab.csv'));
end
